---
# tasks file for roles/nginx
- name: Create Nginx container
  docker_container:
    name: node_exporter
    image: myitam/nginx:"{{ image_tag }}"
    recreate: yes
    ports:
     - "8080:8080"
    restart: yes
    restart_policy: always
    purge_networks: yes
    networks_cli_compatible: yes