  - name: this is lesson21 with using blocks task
    hosts: AWS
    become: true
    roles:
  - name: Unarchive a file
    unarchive:
      src: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
      dst: /home/ubuntu
      remote_src: yes
  - name: add the user 'node_exporter' with a false shell
    user: node_exporter
    shell: /bin/false
    create_home: no  
  - name: copy a node_exporter file
    copy:
     src: /home/ubuntu/node_exporter-1.7.0.linux-amd64/node_exporter
     dest: /usr/local/bin/node_exporter
     mode: a+x
     owner: node_exporter
     group: node_exporter
     remote_src: yes
  - name: copy node_exporter service
    copy:
      src: node_exporter.service
      dest: /etc/systemd/system/node_exporter.service
  - name: just force systemd
    systemd:
      name: node_exporter
      state: started
      deamon_reload: yes
      enabled: yes