services:
  wordpress:
    container_name: wordpress
    depends_on:
      - mysql
    image: wordpress:php8.2
    restart: always
    ports:
      - 8085:80
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html

  mysql:
    image: mysql:8.3
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_ROOT_PASSWORD=wordpress
    volumes:
      - mysql:/var/lib/mysql 

volumes:
  wordpress:
  mysql: