---
# tasks file for roles/nginx
- name: Create Nginx container
  docker_container:
    name: nginx
    image: myitam/nginx:"{{ Image_tag }}"
    recreate: yes
    ports:
     - "80:80"
    restart: yes
    restart_policy: always