name: CI/CD Lesson 23
env:
  Image_tag: ${{ github.run_number }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        cd lesson-23
        docker build . --file Dockerfile --tag arturdavtyan/nginx:${{ env.Image_tag }}

    - name: Login the Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the Docker Hub
      run: docker push arturdavtyan/nginx:${{ env.Image_tag }}