name: TheEnd
env:
  Image_tag: latest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        cd TheEnd
        docker build . --file Dockerfile --tag myitam/nginx:${{ env.Image_tag }}

    - name: Login the Docker Hub
      uses: docker/login-action@v3
      with:
        username: myitam
        password: dckr_pat_0OWrvWHunwS5vKbb4hNOE0hejmI

    - name: Push the Docker Hub
      run: docker push myitam/nginx:${{ env.Image_tag }}